<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\SDM.Core\SDM.Core.csproj" />
    <ProjectReference Include="..\..\src\SDM.Application\SDM.Application.csproj" />
    <ProjectReference Include="..\..\src\SDM.Infrastructure\SDM.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\SDM.Database\SDM.Database.csproj" />
    <ProjectReference Include="..\..\src\SDM.Desktop\SDM.Desktop.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
</Project>
